# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UegHOU87uqC1b9kDAmY8EU08oWXjcjdX
"""

#set password
set_pass = input("set a password for your room:")
re_enter = input("re enter your password to confirm:")
if set_pass == re_enter:
    room_password = set_pass
    print("\nPassword set successfully\nUse it to enter your room")
else:
    print("\nEntered passwords doesn't match\nSet it again")

#trying to enter room using password
c = 3
while(c > 0):
    user = input("Enter your password to access the room:")
    if user == room_password:
        print("\nAccess Successfull.You can now enter your room.")
        break
    else:
        c-=1
        if c!=0:
            print("Oops! Wrong Password.Try Again.",c,"Attempt left.")
        else:
            print("Login Expired.No attempts left.")